### ISSUE TITLE
考虑加个正则解析微信ID的功能

### ISSUE THREAD

**Issue by XY0797** [Replica0110/ECJTU-Calendar#1]
可以考虑参考下我“XY课程表”的设计，在“首页-菜单-设置”用户粘贴链接，利用正则提取微信ID：

![image](https://github.com/user-attachments/assets/97a91f83-f45c-42cf-a217-9ccd2de62bbd)

参考代码：

```js
	function extractWeiXinID(url) {
		const regex = /\?weiXinID=(.+?)(&|$)/;
		const matchResult = url.match(regex);
		if (matchResult) {
			return matchResult[1];
		} else {
			throw new Error('无法识别你的url，您可能复制错了，也可能是本软件已经不支持解析新版的网页');
		}
	}
```

正则参考：`\?weiXinID=(.+?)(&|$)`，第一个子匹配项即为`微信ID`

考虑更新下复制链接的文档，有更方便的方法：

![image](https://github.com/user-attachments/assets/94461da4-aaf1-4292-8597-370a95413ce8)

> 下面是我设计的软件“XY课程表”的下载链接，一年内有效：
> http://43.136.25.224:7302/ecjtuacmdoc/XYCourseSchedule/
> 使用uni-app前端技术构建，作为公益软件发行。填入微信ID后具备从教务系统导入课表(从“我的课表”页面导入)的功能，并且可以自动同步近5天“我的日历”，并且可以智能合并两者。支持识别特殊上课时间段(10:30上课)。
> 欢迎下载体验，交流Q群：310888289
> ![image](https://github.com/user-attachments/assets/7a7e7aec-2a13-49ec-bb24-f34378479441)

**Comment by Replica0110** [comment]
感谢建议，已优化
